### ISSUE TITLE
CRB: Charm spell heightening

### ISSUE THREAD

**Issue by cybermephit** [VestOfHolding/Pathfinder2EOversights#18] opened 2019-10-11 21:09 UTC
The Heightened entries are labeled (+4) and (+8).
This is not consistent and confusing as the effects are not cumulative.
They should be labeled (5th) and (9th) instead, assuming these are the intended levels.

**Comment by LyzLiddell** [comment] 2019-10-11 21:33
> The Heightened entries are labeled (+4) and (+8).
> This is not consistent and confusing as the effects are not cumulative.
> They should be labeled (5th) and (9th) instead, assuming these are the intended levels.

These appear to be errors limited to the Archives of Nethys version of the spell. The _Pathfinder Core Rulebook_ lists them as intended, at **Heightened (4th)** and **Heightened (8th)**.

**Comment by VestOfHolding** [comment] 2019-10-27 22:25
Closing as I can confirm with my own Core book. Nethys should be corrected.

**Closed by VestOfHolding** 2019-10-27 22:25 UTC
